#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

RESEARCH_ROOT="${REPO_ROOT}/research_data"
RAW_ROOT="${RESEARCH_ROOT}/raw"
PROCESSED_ROOT="${RESEARCH_ROOT}/processed"
DIAGRAMS_ROOT="${RESEARCH_ROOT}/diagrams"
REPORTS_ROOT="${RESEARCH_ROOT}/reports"
META_ROOT="${RESEARCH_ROOT}/_meta"
README_ROOT="${RESEARCH_ROOT}/readme"

REPEATS=1
SHORT_DURATION="6m"
MEDIUM_DURATION="12m"
LONG_DURATION="25m"
WITH_PPROF=1
OPEN_UI=0

usage() {
  cat <<'EOF'
Usage:
  scripts/build_full_research_suite.sh [options]

Options:
  --repeats <n>
  --short-duration <dur>
  --medium-duration <dur>
  --long-duration <dur>
  --with-pprof
  --no-pprof
  --open-ui
  --help

Runs all presets (short, medium, long) and all scenarios (baseline, 429, 500),
then aggregates outputs, generates diagrams, and produces final markdown+pdf report.
EOF
}

log() {
  printf '[full_suite] %s\n' "$*"
}

die() {
  printf '[full_suite] ERROR: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --repeats) REPEATS="$2"; shift 2 ;;
      --short-duration) SHORT_DURATION="$2"; shift 2 ;;
      --medium-duration) MEDIUM_DURATION="$2"; shift 2 ;;
      --long-duration) LONG_DURATION="$2"; shift 2 ;;
      --with-pprof) WITH_PPROF=1; shift ;;
      --no-pprof) WITH_PPROF=0; shift ;;
      --open-ui) OPEN_UI=1; shift ;;
      --help|-h) usage; exit 0 ;;
      *) die "unknown argument: $1" ;;
    esac
  done
}

duration_for_preset() {
  local preset="$1"
  case "$preset" in
    short) echo "$SHORT_DURATION" ;;
    medium) echo "$MEDIUM_DURATION" ;;
    long) echo "$LONG_DURATION" ;;
    *) die "unknown preset: $preset" ;;
  esac
}

pprof_flag() {
  [[ "$WITH_PPROF" -eq 1 ]] && echo "--with-pprof" || echo "--no-pprof"
}

open_ui_flag() {
  [[ "$OPEN_UI" -eq 1 ]] && echo "--open-ui" || echo ""
}

ensure_structure() {
  mkdir -p "$RAW_ROOT" "$PROCESSED_ROOT" "$DIAGRAMS_ROOT" "$REPORTS_ROOT" "$META_ROOT" "$README_ROOT"
}

write_readmes() {
  cat >"${RAW_ROOT}/README.md" <<'EOF'
# raw

Contains per-preset and per-scenario raw run outputs generated by runner scripts.

Structure:

- raw/<preset>/<scenario>/
EOF

  cat >"${PROCESSED_ROOT}/README.md" <<'EOF'
# processed

Contains normalized/merged tabular outputs derived from raw Prometheus exports.

Key files:

- run_log_all.csv
- summary_by_run_all.csv
- comparison_table.csv
EOF

  cat >"${DIAGRAMS_ROOT}/README.md" <<'EOF'
# diagrams

Contains generated comparison charts produced by R from processed tables.

Typical files:

- throughput_comparison.png
- latency_comparison.png
- error_rate_comparison.png
- memory_comparison.png
EOF

  cat >"${REPORTS_ROOT}/README.md" <<'EOF'
# reports

Contains textual reports generated from aggregated data.

Key files:

- latest.md
- report.md
EOF

  cat >"${META_ROOT}/README.md" <<'EOF'
# _meta

Contains metadata and manifest files for reproducibility and auditability.
EOF

  cat >"${README_ROOT}/README.md" <<'EOF'
# readme

Contains documentation index/readme assets for this research package.
EOF
}

write_nested_readmes() {
  find "$RAW_ROOT" -type d | while read -r dir; do
    local readme="$dir/README.md"
    if [[ ! -f "$readme" ]]; then
      cat >"$readme" <<EOF
# $(basename "$dir")

Directory path: ${dir#${RESEARCH_ROOT}/}

This directory stores raw artifacts for its preset/scenario/run scope.

Typical files include crawler logs, fixture logs, and exported Prometheus JSON series.
EOF
    fi
  done

  find "$PROCESSED_ROOT" "$DIAGRAMS_ROOT" "$REPORTS_ROOT" "$META_ROOT" "$README_ROOT" -type d | while read -r dir; do
    local readme="$dir/README.md"
    [[ -f "$readme" ]] && continue
    cat >"$readme" <<EOF
# $(basename "$dir")

Directory path: ${dir#${RESEARCH_ROOT}/}

Contains generated artifacts in this category.
EOF
  done
}

run_all_matrix() {
  local presets=(short medium long)
  local scenarios=(baseline 429 500)

  for preset in "${presets[@]}"; do
    local dur
    dur="$(duration_for_preset "$preset")"
    for scenario in "${scenarios[@]}"; do
      local out_dir="${RAW_ROOT}/${preset}/${scenario}"
      mkdir -p "$out_dir"
      log "running preset=${preset} scenario=${scenario} repeats=${REPEATS} duration=${dur}"
      local ui_arg
      ui_arg=""
      if [[ "$OPEN_UI" -eq 1 && "$preset" == "short" && "$scenario" == "baseline" ]]; then
        ui_arg="--open-ui"
      fi

      local cmd=(
        "${SCRIPT_DIR}/run_research.sh"
        --preset "$preset"
        --scenario "$scenario"
        --repeats "$REPEATS"
        --duration "$dur"
        --output-dir "$out_dir"
        "$(pprof_flag)"
      )

      if [[ -n "$ui_arg" ]]; then
        cmd+=("$ui_arg")
      fi

      "${cmd[@]}"
    done
  done
}

generate_meta() {
  {
    echo "generated_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo "repeats=${REPEATS}"
    echo "short_duration=${SHORT_DURATION}"
    echo "medium_duration=${MEDIUM_DURATION}"
    echo "long_duration=${LONG_DURATION}"
    echo "with_pprof=${WITH_PPROF}"
  } >"${META_ROOT}/run_config.env"

  {
    echo "go: $(go version 2>/dev/null || true)"
    echo "python3: $(python3 --version 2>/dev/null || true)"
    echo "Rscript: $(Rscript --version 2>&1 | head -n 1 || true)"
    echo "docker: $(docker --version 2>/dev/null || true)"
  } >"${META_ROOT}/tool_versions.txt"
}

aggregate_and_diagram() {
  python3 "${SCRIPT_DIR}/aggregate_research.py" --raw-root "$RAW_ROOT" --out-root "$RESEARCH_ROOT"
  Rscript "${SCRIPT_DIR}/r/generate_diagrams.R" "${PROCESSED_ROOT}/comparison_table.csv" "$DIAGRAMS_ROOT"
}

build_final_markdown() {
  local final_md="${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.md"
  {
    echo "# Full Research Report"
    echo
    echo "Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
    echo "## Package Overview"
    echo
    echo "This report consolidates all presets (short, medium, long) and scenarios (baseline, 429, 500)."
    echo
    echo "## Latest Snapshot"
    echo
    cat "${REPORTS_ROOT}/latest.md"
    echo
    echo "## Comprehensive Analysis"
    echo
    cat "${REPORTS_ROOT}/report.md"
    echo
    echo "## Processed Tables"
    echo
    echo '- `processed/comparison_table.csv`'
    echo '- `processed/summary_by_run_all.csv`'
    echo '- `processed/run_log_all.csv`'
    echo
    echo "## Diagrams"
    echo
    for img in throughput_comparison.png latency_comparison.png error_rate_comparison.png memory_comparison.png; do
      if [[ -f "${DIAGRAMS_ROOT}/${img}" ]]; then
        echo "### ${img}"
        echo
        echo "![](diagrams/${img})"
        echo
      fi
    done

    echo "## Reproducibility Metadata"
    echo
    echo '- `_meta/run_config.env`'
    echo '- `_meta/tool_versions.txt`'
    echo '- `_meta/manifest.json`'
    echo
    echo "## Explicit Number Interpretation"
    echo
    echo "- visited_rate/discovered_rate are throughput indicators (URLs per second). Higher means faster crawl progression."
    echo "- p95_fetch is tail latency in seconds. Lower means better latency consistency."
    echo "- fetch_error_rate is failures per second. Lower means better stability."
    echo "- rss is resident memory in bytes (converted to MiB in tables). Lower peak indicates better memory efficiency."
    echo "- gc_pause_p99 is p99 GC pause duration in seconds. Lower values indicate lower GC overhead."
  } >"$final_md"
}

render_pdf() {
  local final_pdf="${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.pdf"
  if command -v Rscript >/dev/null 2>&1; then
    Rscript -e "rmarkdown::render('${SCRIPT_DIR}/full_report.Rmd', output_file='${final_pdf}', params=list(root_dir='${RESEARCH_ROOT}'))" || true
  fi

  if [[ ! -f "$final_pdf" ]]; then
    if command -v pandoc >/dev/null 2>&1; then
      pandoc "${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.md" -o "$final_pdf" || true
    fi
  fi

  if [[ ! -f "$final_pdf" ]]; then
    Rscript - <<'EOF'
out <- Sys.getenv("FINAL_PDF")
infile <- Sys.getenv("FINAL_MD")
lines <- readLines(infile, warn = FALSE)
if (length(lines) == 0) lines <- "(empty report)"
pdf(out, width = 8.27, height = 11.69)
on.exit(dev.off(), add = TRUE)
par(mar = c(0.5, 0.5, 0.5, 0.5))
line_idx <- 1
while (line_idx <= length(lines)) {
  plot.new()
  y <- seq(0.98, 0.05, length.out = 55)
  for (i in seq_along(y)) {
    if (line_idx > length(lines)) break
    text(0.01, y[i], labels = substr(lines[line_idx], 1, 120), adj = c(0, 1), cex = 0.7, family = "mono")
    line_idx <- line_idx + 1
  }
}
EOF
  fi

  if [[ ! -f "$final_pdf" ]]; then
    die "unable to generate PDF via rmarkdown, pandoc, or R fallback"
  fi
}

generate_checksums() {
  local out="${META_ROOT}/checksums.sha256"
  (
    cd "$RESEARCH_ROOT"
    find . -type f ! -name "checksums.sha256" -print0 | sort -z | xargs -0 shasum -a 256
  ) >"$out"
}

generate_validation_note() {
  local out="${META_ROOT}/validation.md"
  local missing=0
  {
    echo "# Validation"
    echo
    echo "Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
    for p in "${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.md" "${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.pdf" "${PROCESSED_ROOT}/comparison_table.csv" "${REPORTS_ROOT}/report.md"; do
      if [[ -f "$p" ]]; then
        echo "- OK: ${p#${RESEARCH_ROOT}/}"
      else
        echo "- MISSING: ${p#${RESEARCH_ROOT}/}"
        missing=1
      fi
    done
  } >"$out"

  [[ "$missing" -eq 0 ]] || die "validation failed; missing required outputs"
}

cleanup_root_files() {
  find "$RESEARCH_ROOT" -maxdepth 1 -type f ! -name 'FULL_RESEARCH_REPORT.md' ! -name 'FULL_RESEARCH_REPORT.pdf' -delete
}

finalize_root_files() {
  local final_md="${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.md"
  local final_pdf="${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.pdf"

  [[ -f "$final_md" ]] || die "missing final markdown report"

  [[ -f "$final_pdf" ]] || die "missing final PDF report (install TeX/rmarkdown or pandoc/pdf backend)"
}

main() {
  parse_args "$@"

  require_cmd bash
  require_cmd docker
  require_cmd go
  require_cmd python3
  require_cmd Rscript

  [[ "$REPEATS" =~ ^[0-9]+$ ]] || die "--repeats must be integer"
  [[ "$REPEATS" -gt 0 ]] || die "--repeats must be > 0"

  ensure_structure
  write_readmes
  mkdir -p "${RESEARCH_ROOT}/raw" "${RESEARCH_ROOT}/processed" "${RESEARCH_ROOT}/diagrams" "${RESEARCH_ROOT}/reports" "${RESEARCH_ROOT}/_meta" "${RESEARCH_ROOT}/readme"
  run_all_matrix
  generate_meta
  aggregate_and_diagram
  write_nested_readmes
  build_final_markdown
  export FINAL_PDF="${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.pdf"
  export FINAL_MD="${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.md"
  render_pdf
  generate_checksums
  generate_validation_note
  finalize_root_files
  cleanup_root_files

  log "full research suite complete"
  log "root outputs: ${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.md and ${RESEARCH_ROOT}/FULL_RESEARCH_REPORT.pdf"
}

main "$@"
