package main

import (
	"flag"
	"fmt"
	"log"
	"net/http"
	"strconv"
	"strings"
	"sync/atomic"
	"time"
)

type config struct {
	Port       int
	Depth      int
	Branching  int
	Latency    time.Duration
	StatusMode string
	StatusN    int
}

type serverState struct {
	requestSeq atomic.Uint64
}

func main() {
	cfg := parseConfig()
	state := &serverState{}

	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", healthzHandler)
	mux.HandleFunc("/robots.txt", robotsHandler)
	mux.HandleFunc("/", pageHandler(cfg, state))

	addr := fmt.Sprintf(":%d", cfg.Port)
	log.Printf("fixture_server listening on %s (depth=%d branching=%d latency=%s status_mode=%s status_n=%d)", addr, cfg.Depth, cfg.Branching, cfg.Latency, cfg.StatusMode, cfg.StatusN)

	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatalf("fixture server failed: %v", err)
	}
}

func parseConfig() config {
	var cfg config

	flag.IntVar(&cfg.Port, "port", 18080, "HTTP port for fixture server")
	flag.IntVar(&cfg.Depth, "depth", 4, "Maximum graph depth generated by fixture")
	flag.IntVar(&cfg.Branching, "branching", 5, "Number of outgoing links per node")
	flag.DurationVar(&cfg.Latency, "latency", 50*time.Millisecond, "Fixed latency per response")
	flag.StringVar(&cfg.StatusMode, "status-mode", "none", "Deterministic response mode: none,429_every_n,500_every_n")
	flag.IntVar(&cfg.StatusN, "status-n", 20, "Every Nth page request returns injected status for status modes")
	flag.Parse()

	if cfg.Port <= 0 {
		cfg.Port = 18080
	}
	if cfg.Depth < 0 {
		cfg.Depth = 0
	}
	if cfg.Branching <= 0 {
		cfg.Branching = 1
	}
	if cfg.Latency < 0 {
		cfg.Latency = 0
	}

	cfg.StatusMode = strings.ToLower(strings.TrimSpace(cfg.StatusMode))
	if cfg.StatusMode != "none" && cfg.StatusMode != "429_every_n" && cfg.StatusMode != "500_every_n" {
		cfg.StatusMode = "none"
	}
	if cfg.StatusN <= 0 {
		cfg.StatusN = 20
	}

	return cfg
}

func healthzHandler(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte("ok\n"))
}

func robotsHandler(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte("User-agent: *\nAllow: /\n"))
}

func pageHandler(cfg config, state *serverState) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(cfg.Latency)
		seq := state.requestSeq.Add(1)
		w.Header().Set("X-Fixture-Req-Seq", fmt.Sprintf("%d", seq))

		if shouldInjectStatus(cfg, seq) {
			w.Header().Set("Content-Type", "text/plain; charset=utf-8")
			w.WriteHeader(injectedStatusCode(cfg))
			_, _ = w.Write([]byte("injected status response\n"))
			return
		}

		path := r.URL.Path
		if path == "/" {
			writePage(w, cfg, 0, 0)
			return
		}

		if strings.HasPrefix(path, "/node/") {
			level, id, ok := parseNodePath(path)
			if !ok {
				http.NotFound(w, r)
				return
			}

			if level < 0 || level > cfg.Depth {
				http.NotFound(w, r)
				return
			}

			writePage(w, cfg, level, id)
			return
		}

		http.NotFound(w, r)
	}
}

func shouldInjectStatus(cfg config, seq uint64) bool {
	if cfg.StatusMode == "none" {
		return false
	}
	if cfg.StatusN <= 0 {
		return false
	}

	return seq%uint64(cfg.StatusN) == 0
}

func injectedStatusCode(cfg config) int {
	switch cfg.StatusMode {
	case "429_every_n":
		return http.StatusTooManyRequests
	case "500_every_n":
		return http.StatusInternalServerError
	default:
		return http.StatusOK
	}
}

func parseNodePath(path string) (int, int, bool) {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	if len(parts) != 3 || parts[0] != "node" {
		return 0, 0, false
	}

	level, err := strconv.Atoi(parts[1])
	if err != nil {
		return 0, 0, false
	}

	id, err := strconv.Atoi(parts[2])
	if err != nil {
		return 0, 0, false
	}

	return level, id, true
}

func writePage(w http.ResponseWriter, cfg config, level int, id int) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)

	var builder strings.Builder
	builder.WriteString("<html><body>\n")
	builder.WriteString(fmt.Sprintf("<h1>node-%d-%d</h1>\n", level, id))

	if level < cfg.Depth {
		baseID := id * cfg.Branching
		for i := 0; i < cfg.Branching; i++ {
			nextID := baseID + i
			nextLevel := level + 1
			builder.WriteString(fmt.Sprintf("<a href=\"/node/%d/%d\">node-%d-%d</a><br/>\n", nextLevel, nextID, nextLevel, nextID))
		}

		crossID := id
		if crossID > 0 {
			crossID--
		}
		builder.WriteString(fmt.Sprintf("<a href=\"/node/%d/%d\">cross-%d-%d</a><br/>\n", level, crossID, level, crossID))
	}

	builder.WriteString("</body></html>")
	_, _ = w.Write([]byte(builder.String()))
}
